languageCode = "en-US"
title = "RootWire "
baseurl = "http://10.142.0.3/"
theme = "code-editor"

[params]
    author = "Brock Ramsey"
    locale = "en-US"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.
